DROP DATABASE IF EXISTS jokes;
CREATE DATABASE jokes;

USE jokes;

CREATE TABLE userjokes(
id INT AUTO_INCREMENT PRIMARY KEY,
title VARCHAR (30) NOT NULL,
up_votes INTEGER,
down_votes INTEGER
);
SELECT * FROM userjokes;

